server:
  port: 9001
  #???????? ??????? ??????????
  shutdown: graceful
  tomcat:
    #  ????-??? ??????????: 2 ?
    connection-timeout: 2s
    #  ????-??? ??????????? ??????????: 15 ?
    keep-alive-timeout: 15s
    threads:
      max: 50
      # ??? ?????
      min-spare: 5

spring:
  application:
    name: pbs-catalog-service