apiVersion: v1
kind: Service
metadata:
  name: pbs-catalog-service-svc
  labels:
    app: pbs-catalog-service-svc
spec:
  type: LoadBalancer
  selector:
    app: pbs-catalog-service-pod
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP